name: "Cachix"
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: ilya-fedin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: NIXPKGS_ALLOW_UNFREE=1 nix-build non-broken.nix
