name: "Cachix"
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git config --global user.email "action@github.com"
    - run: git config --global user.name "GitHub Action"
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: nix flake update
    - uses: cachix/cachix-action@v10
      with:
        name: ilya-fedin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: NIXPKGS_ALLOW_UNFREE=1 nix-build non-broken.nix
    - run: git add flake.lock
    - run: git diff --staged --quiet || (git commit -m "Update flake" && git push)
