name: "Cachix"
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
    - run: nix flake update
    - uses: actions/cache@v3
      with:
        path: flake.lock
        key: ${{ hashFiles('flake.lock') }}

  tests:
    needs: update-flake
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
    - uses: actions/cache@v3
      with:
        path: flake.lock
        key: ${{ hashFiles('flake.lock') }}
    - uses: cachix/cachix-action@v10
      with:
        name: ilya-fedin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: NIXPKGS_ALLOW_UNFREE=1 nix-build non-broken.nix

  push-flake-update:
    needs: [update-flake, tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: flake.lock
        key: ${{ hashFiles('flake.lock') }}
    - run: git config --global user.email "action@github.com"
    - run: git config --global user.name "GitHub Action"
    - run: git add flake.lock
    - run: git diff --staged --quiet || (git commit -m "Update flake" && git push)
